# Generated by Django 6.1 on 2026-08-26 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Facility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('facility_type', models.CharField(default='PHC', max_length=100)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('distance_km', models.FloatField(default=10.0)),
                ('has_specialist', models.BooleanField(default=True)),
                ('match_score', models.IntegerField(default=90)),
            ],
        ),
        migrations.CreateModel(
            name='MedicineStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('dosage', models.CharField(default='500mg', max_length=50)),
                ('is_available', models.BooleanField(default=True)),
                ('quantity', models.IntegerField(default=100)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medicines', to='api.facility')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_id', models.CharField(max_length=30, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other'), ('None', 'Prefer not to say')], default='None', max_length=20)),
                ('phone', models.CharField(db_index=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('address', models.TextField(blank=True, default='')),
                ('village', models.CharField(max_length=150)),
                ('district', models.CharField(max_length=150)),
                ('blood_group', models.CharField(default='Not Added', max_length=10)),
                ('allergies', models.CharField(default='No allergies recorded', max_length=255)),
                ('active_conditions', models.CharField(default='No active conditions', max_length=255)),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('hi', 'Hindi'), ('te', 'Telugu'), ('mr', 'Marathi')], default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='HealthTimelineRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_type', models.CharField(choices=[('CONSULTATION', 'PHC / Specialist Consultation'), ('LAB_TEST', 'Lab Test'), ('REFERRAL', 'Referral Created'), ('FOLLOW_UP', 'Follow-up Scheduled')], max_length=30)),
                ('title', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('Completed', 'Completed'), ('Available', 'Available'), ('Pending', 'Pending'), ('Upcoming', 'Upcoming')], default='Completed', max_length=30)),
                ('event_date', models.DateField()),
                ('facility_name', models.CharField(max_length=200)),
                ('doctor_name', models.CharField(blank=True, max_length=150, null=True)),
                ('health_issue', models.CharField(blank=True, max_length=255, null=True)),
                ('diagnosis', models.TextField(blank=True, null=True)),
                ('test_name', models.CharField(blank=True, max_length=200, null=True)),
                ('test_result', models.CharField(blank=True, max_length=255, null=True)),
                ('prescription', models.TextField(blank=True, null=True)),
                ('referral_source', models.CharField(blank=True, max_length=150, null=True)),
                ('referral_target', models.CharField(blank=True, max_length=150, null=True)),
                ('referral_reason', models.TextField(blank=True, null=True)),
                ('risk_level', models.CharField(default='Medium', max_length=50)),
                ('followup_purpose', models.TextField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline_records', to='api.patient')),
            ],
            options={
                'ordering': ['-event_date'],
            },
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_name', models.CharField(max_length=150)),
                ('appointment_time', models.DateTimeField()),
                ('queue_number', models.CharField(default='A-17', max_length=20)),
                ('patients_ahead', models.IntegerField(default=4)),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.facility')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='SOSAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.patient')),
            ],
        ),
    ]
