# Generated by Django 6.1.1 on 2026-09-06 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_hospitaladminprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auditlog',
            name='action',
            field=models.CharField(choices=[('LOGIN_SUCCESS', 'Login success'), ('LOGIN_FAILURE', 'Login failure'), ('LOGOUT', 'Logout'), ('PATIENT_VIEWED', 'Patient record viewed'), ('PATIENT_CREATED', 'Patient record created'), ('PATIENT_UPDATED', 'Patient record updated'), ('PATIENT_DELETED', 'Patient record deleted'), ('DOCTOR_CREATED', 'Doctor account created'), ('HOSPITAL_ADMIN_CREATED', 'Hospital admin account created'), ('UNAUTHORIZED_ACCESS', 'Unauthorized access attempt'), ('PERMISSION_DENIED', 'Permission denied')], max_length=40),
        ),
    ]
