# Generated by Django 6.1.1 on 2026-09-10 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_phcprofile_referringphc'),
    ]

    operations = [
        migrations.CreateModel(
            name='DigitalTriageAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_symptom', models.CharField(max_length=200)),
                ('duration', models.CharField(blank=True, default='', max_length=80)),
                ('additional_symptoms', models.JSONField(blank=True, default=list)),
                ('follow_up_answers', models.JSONField(blank=True, default=list)),
                ('priority', models.CharField(choices=[('EMERGENCY', 'Emergency'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=20)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('NEW', 'New'), ('REVIEWED', 'Reviewed'), ('RESOLVED', 'Resolved')], default='NEW', max_length=20)),
                ('source', models.CharField(default='patient_portal', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='digital_triage_assessments', to='api.patient')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
