# Generated by Django 6.1.1 on 2026-09-11 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_hospitalstaff_equipment_medicine_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='BedResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('total', models.PositiveIntegerField()),
                ('occupied', models.PositiveIntegerField(default=0)),
                ('facility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bed_resources', to='api.facility')),
            ],
        ),
    ]
