# Generated by Django 6.1.1 on 2026-09-06 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('PATIENT', 'Patient'), ('DOCTOR', 'Doctor'), ('ADMIN', 'Admin'), ('HOSPITAL_ADMIN', 'Hospital Admin')], default='PATIENT', max_length=20),
        ),
    ]
